VALID_TARGETS = [
    "Atheism",
    "Climate Change",
    "Healthcare Reform",
    "Government Policies",
    "Education System",
    "Gun Control",
    "Tax Policy",
    "Economic Policy",
    "Immigration",
    "Racial Equality",
    "Universal Basic Income",
    "Gun Control Laws",
    "Affordable Housing",
    "Free Healthcare",
    "Freedom of Speech",
    "LGBTQ+ Rights",
    "Religious Freedom",
    "Press Freedom",
    "Digital Privacy",
    "Censorship",
    "Electoral Reform",
    "Labor Rights",
    "Wealth Inequality",
    "Artificial Intelligence Ethics",
    "Renewable Energy Policies",
    "Water Rights",
    "Military Spending",
    "Corporate Regulation",
    "Public Transportation",
    "Food Security",
    "Women's Rights",
    "Child Labor Laws",
    "Animal Rights",
    "Drug Policy Reform",
    "Cybersecurity Policies",
    "National Security",
    "Space Exploration Policies",
    "Prison Reform",
    "Death Penalty",
    "Terrorism Laws",
    "Whistleblower Protection",
    "Judicial Independence",
    "Cultural Heritage Protection",
    "Social Media Regulation",
    "Refugee Rights",
    "Pension Reform",
    "Youth Engagement in Politics",
    "Foreign Aid Policies",
    "Anti-Corruption Measures",
    "Digital Currency Regulation",
    "Automation and Job Displacement",
    "Crisis Response Policies",
]
